import { NewsFeed } from '../../components/news/NewsFeed'
import styles from './NewsPage.module.css'

export function NewsPage() {
  return (
    <>
      <section className={styles.hero}>
        <div className="container">
          <p className="eyebrow">From the desk</p>
          <h1 className={styles.title}>News</h1>
          <p className={styles.lead}>
            Tournaments, club notes, and chess culture — posted by the hall’s editors,
            not generated by the front end.
          </p>
        </div>
      </section>

      <section className={`band band--dim ${styles.feedBand}`}>
        <div className="container">
          <NewsFeed />
        </div>
      </section>
    </>
  )
}
